version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: America/New_York
  open-pull-requests-limit: 99
  target-branch: develop
  reviewers:
  - ZachTRice
  versioning-strategy: increase
  ignore:
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.5
    - 1.3.6
    - 1.3.7
    - 1.3.8
    - 1.3.9
    - 1.4.0
    - 1.4.1
    - 1.5.0
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.1
